/**
 * Deterministic seed fixtures — stable IDs and phone numbers for idempotent reseeding.
 * Categories: English labels (matches frontend categoryFirestoreValue).
 * Cities: slug IDs (matches frontend CITIES).
 */

export const SEED_USER_PASSWORD_DEFAULT = 'Seed123!';

export const CATEGORY_LABELS = [
  'Agriculture',
  'Real Estate',
  'Vehicles',
  'Electronics',
  'Fashion',
  'Home',
  'Kids & Baby',
  'Jobs',
  'Services',
  'Rugs',
  'Others',
];

export const CITY_IDS = [
  'casablanca',
  'rabat',
  'fes',
  'marrakech',
  'tangier',
  'agadir',
  'meknes',
  'oujda',
  'kenitra',
  'tetouan',
  'sale',
  'nador',
  'mohammedia',
  'beni-mellal',
  'el-jadida',
];

/** Fixed UUIDs — never change these or upsert keys break. */
export const USER_IDS = {
  superAdmin: 'a1000001-0000-4000-8000-000000000001',
  admin: 'a1000002-0000-4000-8000-000000000002',
  sellerPro1: 'a1000003-0000-4000-8000-000000000003',
  sellerPro2: 'a1000004-0000-4000-8000-000000000004',
  sellerPro3: 'a1000005-0000-4000-8000-000000000005',
  sellerPro4: 'a1000006-0000-4000-8000-000000000006',
  sellerPro5: 'a1000007-0000-4000-8000-000000000007',
  sellerPro6: 'a1000008-0000-4000-8000-000000000008',
  sellerPro7: 'a1000009-0000-4000-8000-000000000009',
  sellerPro8: 'a1000010-0000-4000-8000-000000000010',
  sellerReg1: 'a1000011-0000-4000-8000-000000000011',
  sellerReg2: 'a1000012-0000-4000-8000-000000000012',
  sellerReg3: 'a1000013-0000-4000-8000-000000000013',
  sellerReg4: 'a1000014-0000-4000-8000-000000000014',
  buyer1: 'a1000015-0000-4000-8000-000000000015',
  buyer2: 'a1000016-0000-4000-8000-000000000016',
  buyer3: 'a1000017-0000-4000-8000-000000000017',
  buyer4: 'a1000018-0000-4000-8000-000000000018',
};

export function buildUserFixtures(superAdminPhone) {
  return [
    {
      id: USER_IDS.superAdmin,
      phoneNumber: superAdminPhone,
      displayName: 'Super Admin',
      role: 'ADMIN',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 150,
    },
    {
      id: USER_IDS.admin,
      phoneNumber: '+212610000001',
      displayName: 'Youssef El Amrani',
      role: 'ADMIN',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 140,
    },
    {
      id: USER_IDS.sellerPro1,
      phoneNumber: '+212610000002',
      displayName: 'Fatima Bennani',
      role: 'USER',
      isPro: true,
      shopName: 'Bennani Auto Casa',
      avatarKey: 'sellerPro1',
      shopDescription: 'Véhicules d\'occasion contrôlés à Casablanca. Livraison possible dans tout le pays.',
      createdDaysAgo: 120,
    },
    {
      id: USER_IDS.sellerPro2,
      phoneNumber: '+212610000003',
      displayName: 'Karim Alaoui',
      role: 'USER',
      isPro: true,
      shopName: 'Alaoui Immobilier',
      avatarKey: 'sellerPro2',
      shopDescription: 'Appartements et villas à Rabat et Salé. Visites virtuelles disponibles.',
      createdDaysAgo: 115,
    },
    {
      id: USER_IDS.sellerPro3,
      phoneNumber: '+212610000004',
      displayName: 'Sanae Idrissi',
      role: 'USER',
      isPro: true,
      shopName: 'TechMaroc by Sanae',
      avatarKey: 'sellerPro3',
      shopDescription: 'Smartphones, laptops et accessoires reconditionnés avec garantie 6 mois.',
      createdDaysAgo: 110,
    },
    {
      id: USER_IDS.sellerPro4,
      phoneNumber: '+212610000005',
      displayName: 'Hassan Tazi',
      role: 'USER',
      isPro: true,
      shopName: 'Tazi Tapis & Déco',
      avatarKey: 'sellerPro4',
      shopDescription: 'Tapis berbères authentiques et décoration artisanale de Fès.',
      createdDaysAgo: 105,
    },
    {
      id: USER_IDS.sellerPro5,
      phoneNumber: '+212610000006',
      displayName: 'Nadia Cherkaoui',
      role: 'USER',
      isPro: true,
      shopName: 'Mode Nadia',
      avatarKey: 'sellerPro5',
      shopDescription: 'Caftans, jellabas et prêt-à-porter féminin à Marrakech.',
      createdDaysAgo: 100,
    },
    {
      id: USER_IDS.sellerPro6,
      phoneNumber: '+212610000007',
      displayName: 'Omar Benjelloun',
      role: 'USER',
      isPro: true,
      shopName: 'Maison Benjelloun',
      avatarKey: 'sellerPro6',
      shopDescription: 'Meubles salon, cuisine équipée et électroménager à Tanger.',
      createdDaysAgo: 95,
    },
    {
      id: USER_IDS.sellerPro7,
      phoneNumber: '+212610000008',
      displayName: 'Laila Amrani',
      role: 'USER',
      isPro: true,
      shopName: 'Petits Trésors Agadir',
      avatarKey: 'sellerPro7',
      shopDescription: 'Puériculture, jouets et vêtements enfants 0–12 ans.',
      createdDaysAgo: 90,
    },
    {
      id: USER_IDS.sellerPro8,
      phoneNumber: '+212610000009',
      displayName: 'Rachid El Fassi',
      role: 'USER',
      isPro: true,
      shopName: 'Services Fassi Pro',
      avatarKey: 'sellerPro8',
      shopDescription: 'Plomberie, électricité et rénovation intérieure à Meknès.',
      createdDaysAgo: 85,
    },
    {
      id: USER_IDS.sellerReg1,
      phoneNumber: '+212610000010',
      displayName: 'Amina Zahraoui',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 60,
    },
    {
      id: USER_IDS.sellerReg2,
      phoneNumber: '+212610000011',
      displayName: 'Mehdi Berrada',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 45,
    },
    {
      id: USER_IDS.sellerReg3,
      phoneNumber: '+212610000012',
      displayName: 'Kenza Mouline',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 30,
    },
    {
      id: USER_IDS.sellerReg4,
      phoneNumber: '+212610000013',
      displayName: 'Yassine Ouazzani',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 14,
      pendingOnlySeller: true,
    },
    {
      id: USER_IDS.buyer1,
      phoneNumber: '+212610000014',
      displayName: 'Salma Harti',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 70,
    },
    {
      id: USER_IDS.buyer2,
      phoneNumber: '+212610000015',
      displayName: 'Adil Chakir',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 55,
    },
    {
      id: USER_IDS.buyer3,
      phoneNumber: '+212610000016',
      displayName: 'Houda Bensaid',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 40,
    },
    {
      id: USER_IDS.buyer4,
      phoneNumber: '+212610000017',
      displayName: 'Tarik El Ghazi',
      role: 'USER',
      isPro: false,
      shopName: '',
      shopLogoUrl: '',
      shopDescription: null,
      createdDaysAgo: 20,
      noFavorites: true,
    },
  ];
}

/** 55 listing blueprints — videoKey overrides in seed-media.js CATEGORY_VIDEO_KEY */
export const LISTING_BLUEPRINTS = [
  { key: 'l01', owner: 'sellerPro1', title: 'Dacia Logan 2019 — 68 000 km, première main', category: 'Vehicles', city: 'casablanca', priceMad: 118000, status: 'APPROVED', daysAgo: 95, views: 1842 },
  { key: 'l02', owner: 'sellerPro1', title: 'Renault Clio 4 diesel — très bon état', category: 'Vehicles', city: 'casablanca', priceMad: 89000, videoKey: 'vehiclesAlt', status: 'APPROVED', daysAgo: 88, views: 1204 },
  { key: 'l03', owner: 'sellerPro1', title: 'Peugeot 208 2021 — garantie constructeur', category: 'Vehicles', city: 'mohammedia', priceMad: 156000, status: 'APPROVED', daysAgo: 72, views: 967 },
  { key: 'l04', owner: 'sellerPro1', title: 'Hyundai i10 2018 — idéal ville', category: 'Vehicles', city: 'casablanca', priceMad: 72000, videoKey: 'vehiclesAlt', status: 'PENDING', daysAgo: 3, views: null },
  { key: 'l05', owner: 'sellerPro1', title: 'Dacia Sandero 2017 — à rénover légèrement', category: 'Vehicles', city: 'casablanca', priceMad: 58000, videoKey: null, status: 'REJECTED', daysAgo: 40, views: 45 },
  { key: 'l06', owner: 'sellerPro2', title: 'Appartement 3 chambres — Hay Riad, Rabat', category: 'Real Estate', city: 'rabat', priceMad: 1450000, status: 'APPROVED', daysAgo: 102, views: 3210 },
  { key: 'l07', owner: 'sellerPro2', title: 'Studio meublé — Agdal, proche tram', category: 'Real Estate', city: 'rabat', priceMad: 420000, status: 'APPROVED', daysAgo: 78, views: 1567 },
  { key: 'l08', owner: 'sellerPro2', title: 'Villa avec piscine — Salé', category: 'Real Estate', city: 'sale', priceMad: 3200000, videoKey: 'pixabaySunset', status: 'APPROVED', daysAgo: 65, views: 2890 },
  { key: 'l09', owner: 'sellerPro2', title: 'Terrain constructible 400 m² — Témara', category: 'Real Estate', city: 'rabat', priceMad: 680000, videoKey: null, status: 'PENDING', daysAgo: 5, views: null },
  { key: 'l10', owner: 'sellerPro2', title: 'Local commercial — centre-ville Rabat', category: 'Real Estate', city: 'rabat', priceMad: 890000, videoKey: null, status: 'REJECTED', daysAgo: 22, views: 112 },
  { key: 'l11', owner: 'sellerPro3', title: 'iPhone 14 Pro 256 Go — débloqué, état neuf', category: 'Electronics', city: 'casablanca', priceMad: 9800, status: 'APPROVED', daysAgo: 55, views: 4102 },
  { key: 'l12', owner: 'sellerPro3', title: 'MacBook Air M2 2023 — 8 Go / 256 Go', category: 'Electronics', city: 'casablanca', priceMad: 11200, status: 'APPROVED', daysAgo: 48, views: 2234 },
  { key: 'l13', owner: 'sellerPro3', title: 'Samsung Galaxy S23 Ultra — avec facture', category: 'Electronics', city: 'rabat', priceMad: 8500, status: 'APPROVED', daysAgo: 41, views: 1876 },
  { key: 'l14', owner: 'sellerPro3', title: 'PlayStation 5 + 2 manettes', category: 'Electronics', city: 'marrakech', priceMad: 5200, videoKey: null, status: 'APPROVED', daysAgo: 35, views: 934 },
  { key: 'l15', owner: 'sellerPro3', title: 'iPad Air 5 — Wi-Fi 64 Go', category: 'Electronics', city: 'casablanca', priceMad: 6200, status: 'ACTIVE', daysAgo: 28, views: 567 },
  { key: 'l16', owner: 'sellerPro3', title: 'Écouteurs Sony WH-1000XM5', category: 'Electronics', city: 'fes', priceMad: 2800, videoKey: null, status: 'PENDING', daysAgo: 2, views: null },
  { key: 'l17', owner: 'sellerPro4', title: 'Tapis berbère Beni Ourain — 2,5 × 1,8 m', category: 'Rugs', city: 'fes', priceMad: 18500, status: 'APPROVED', daysAgo: 90, views: 1456 },
  { key: 'l18', owner: 'sellerPro4', title: 'Tapis Azilal coloré — fait main', category: 'Rugs', city: 'fes', priceMad: 9200, status: 'APPROVED', daysAgo: 76, views: 892 },
  { key: 'l19', owner: 'sellerPro4', title: 'Kilim vintage — salon 3 × 2 m', category: 'Rugs', city: 'marrakech', priceMad: 7400, videoKey: null, status: 'APPROVED', daysAgo: 62, views: 654 },
  { key: 'l20', owner: 'sellerPro4', title: 'Tapis Boucherouite recyclé', category: 'Rugs', city: 'fes', priceMad: 4800, status: 'ACTIVE', daysAgo: 50, views: 321 },
  { key: 'l21', owner: 'sellerPro5', title: 'Caftan brodé main — taille M', category: 'Fashion', city: 'marrakech', priceMad: 3200, status: 'APPROVED', daysAgo: 84, views: 1102 },
  { key: 'l22', owner: 'sellerPro5', title: 'Jellaba homme en lin — été 2026', category: 'Fashion', city: 'marrakech', priceMad: 890, videoKey: null, status: 'APPROVED', daysAgo: 70, views: 445 },
  { key: 'l23', owner: 'sellerPro5', title: 'Sac à main cuir marocain artisanal', category: 'Fashion', city: 'marrakech', priceMad: 1450, status: 'APPROVED', daysAgo: 58, views: 678 },
  { key: 'l24', owner: 'sellerPro5', title: 'Babouches traditionnelles — plusieurs tailles', category: 'Fashion', city: 'fes', priceMad: 350, videoKey: null, status: 'PENDING', daysAgo: 4, views: null },
  { key: 'l25', owner: 'sellerPro5', title: 'Robe de soirée — collection limitée', category: 'Fashion', city: 'casablanca', priceMad: 2100, videoKey: null, status: 'REJECTED', daysAgo: 18, views: 89 },
  { key: 'l26', owner: 'sellerPro6', title: 'Canapé d\'angle 5 places — tissu gris', category: 'Home', city: 'tangier', priceMad: 8900, status: 'APPROVED', daysAgo: 80, views: 756 },
  { key: 'l27', owner: 'sellerPro6', title: 'Table à manger bois massif — 6 chaises', category: 'Home', city: 'tangier', priceMad: 6200, status: 'APPROVED', daysAgo: 66, views: 534 },
  { key: 'l28', owner: 'sellerPro6', title: 'Réfrigérateur Samsung No Frost 400 L', category: 'Home', city: 'tangier', priceMad: 5400, videoKey: null, status: 'APPROVED', daysAgo: 52, views: 412 },
  { key: 'l29', owner: 'sellerPro6', title: 'Lave-linge Bosch 8 kg', category: 'Home', city: 'tetouan', priceMad: 3800, videoKey: null, status: 'ACTIVE', daysAgo: 38, views: 198 },
  { key: 'l30', owner: 'sellerPro6', title: 'Armoire dressing 3 portes', category: 'Home', city: 'tangier', priceMad: 2900, videoKey: null, status: 'PENDING', daysAgo: 1, views: null },
  { key: 'l31', owner: 'sellerPro7', title: 'Poussette Bugaboo Fox 3 — complète', category: 'Kids & Baby', city: 'agadir', priceMad: 7800, status: 'APPROVED', daysAgo: 74, views: 623 },
  { key: 'l32', owner: 'sellerPro7', title: 'Lit bébé évolutif en bois', category: 'Kids & Baby', city: 'agadir', priceMad: 2200, videoKey: null, status: 'APPROVED', daysAgo: 60, views: 389 },
  { key: 'l33', owner: 'sellerPro7', title: 'Lot vêtements fille 2–4 ans — 15 pièces', category: 'Kids & Baby', city: 'agadir', priceMad: 450, videoKey: null, status: 'APPROVED', daysAgo: 46, views: 267 },
  { key: 'l34', owner: 'sellerPro7', title: 'Siège auto groupe 1/2/3', category: 'Kids & Baby', city: 'marrakech', priceMad: 1650, status: 'ACTIVE', daysAgo: 32, views: 145 },
  { key: 'l35', owner: 'sellerPro8', title: 'Plombier certifié — dépannage 24h/24', category: 'Services', city: 'meknes', priceMad: 0, videoKey: null, status: 'APPROVED', daysAgo: 100, views: 890 },
  { key: 'l36', owner: 'sellerPro8', title: 'Électricien — installation et mise aux normes', category: 'Services', city: 'meknes', priceMad: 0, videoKey: null, status: 'APPROVED', daysAgo: 85, views: 567 },
  { key: 'l37', owner: 'sellerPro8', title: 'Peinture intérieure — devis gratuit', category: 'Services', city: 'fes', priceMad: 0, videoKey: null, status: 'PENDING', daysAgo: 6, views: null },
  { key: 'l38', owner: 'sellerPro8', title: 'Carrelage et faïence — pose incluse', category: 'Services', city: 'meknes', priceMad: 0, videoKey: null, status: 'REJECTED', daysAgo: 25, views: 34 },
  { key: 'l39', owner: 'sellerReg1', title: 'Vélo VTT Decathlon — peu utilisé', category: 'Others', city: 'kenitra', priceMad: 1800, videoKey: null, status: 'APPROVED', daysAgo: 44, views: 234 },
  { key: 'l40', owner: 'sellerReg1', title: 'Guitare acoustique Yamaha F310', category: 'Others', city: 'kenitra', priceMad: 1200, videoKey: null, status: 'APPROVED', daysAgo: 36, views: 178 },
  { key: 'l41', owner: 'sellerReg2', title: 'Appartement à louer — 2 chambres Oujda', category: 'Real Estate', city: 'oujda', priceMad: 4500, status: 'APPROVED', daysAgo: 42, views: 512, description: 'Location mensuelle. Charges comprises.' },
  { key: 'l42', owner: 'sellerReg2', title: 'Scooter Yamaha NMAX 125', category: 'Vehicles', city: 'oujda', priceMad: 22000, videoKey: 'vehiclesAlt', status: 'PENDING', daysAgo: 7, views: null },
  { key: 'l43', owner: 'sellerReg3', title: 'Commis de cuisine — offre d\'emploi', category: 'Jobs', city: 'casablanca', priceMad: 0, videoKey: null, status: 'APPROVED', daysAgo: 30, views: 1456, description: 'Restaurant gastronomique cherche commis motivé. Expérience souhaitée.' },
  { key: 'l44', owner: 'sellerReg3', title: 'Développeur React — télétravail partiel', category: 'Jobs', city: 'rabat', priceMad: 0, videoKey: null, status: 'PENDING', daysAgo: 8, views: null },
  { key: 'l45', owner: 'sellerReg4', title: 'Table basse en fer forgé — artisanat local', category: 'Home', city: 'el-jadida', priceMad: 1650, videoKey: null, status: 'PENDING', daysAgo: 2, views: null },
  { key: 'l46', owner: 'sellerReg4', title: 'Miroir salon doré — style marocain', category: 'Home', city: 'el-jadida', priceMad: 980, videoKey: null, status: 'PENDING', daysAgo: 1, views: null },
  { key: 'l47', owner: 'sellerReg4', title: 'Lampe artisanale en cuivre', category: 'Home', city: 'el-jadida', priceMad: 620, videoKey: null, status: 'PENDING', daysAgo: 1, views: null },
  { key: 'l48', owner: 'sellerPro1', title: 'Citroën C3 2020 — climatisation', category: 'Vehicles', city: 'casablanca', priceMad: 132000, status: 'APPROVED', daysAgo: 25, views: 445 },
  { key: 'l49', owner: 'sellerPro3', title: 'Apple Watch Series 9 GPS 45 mm', category: 'Electronics', city: 'casablanca', priceMad: 4200, status: 'APPROVED', daysAgo: 20, views: 678 },
  { key: 'l50', owner: 'sellerPro2', title: 'Duplex 4 chambres — Californie, Casablanca', category: 'Real Estate', city: 'casablanca', priceMad: 2100000, videoKey: 'pixabaySunset', status: 'APPROVED', daysAgo: 15, views: 1890 },
  { key: 'l51', owner: 'sellerPro4', title: 'Tapis Zanafi noir et blanc — salon', category: 'Rugs', city: 'marrakech', priceMad: 11200, status: 'APPROVED', daysAgo: 12, views: 423 },
  { key: 'l52', owner: 'sellerPro5', title: 'Takchita de mariage — location ou vente', category: 'Fashion', city: 'casablanca', priceMad: 8500, status: 'APPROVED', daysAgo: 8, views: 890 },
  { key: 'l53', owner: 'sellerPro6', title: 'Bureau ergonomique + fauteuil', category: 'Home', city: 'rabat', priceMad: 3400, status: 'ACTIVE', daysAgo: 6, views: 156 },
  { key: 'l54', owner: 'sellerPro7', title: 'Landau bébé 3 en 1', category: 'Kids & Baby', city: 'agadir', priceMad: 1950, videoKey: null, status: 'APPROVED', daysAgo: 4, views: 89 },
  { key: 'l55', owner: 'sellerPro8', title: 'Climatisation split 12000 BTU — pose', category: 'Services', city: 'casablanca', priceMad: 0, videoKey: null, status: 'ACTIVE', daysAgo: 2, views: 67 },
];

export const CHAT_SCENARIOS = [
  {
    key: 't01',
    listingKey: 'l01',
    buyer: 'buyer1',
    messages: [
      { sender: 'buyer1', text: 'Bonjour, la Logan est-elle toujours disponible ?', hoursAgo: 72 },
      { sender: 'sellerPro1', text: 'Oui, disponible. Vous pouvez passer la voir ce week-end à Bouskoura.', hoursAgo: 70 },
      { sender: 'buyer1', text: 'Parfait, samedi 10h ça vous convient ?', hoursAgo: 68 },
      { sender: 'sellerPro1', text: 'Oui, je vous envoie l\'adresse en MP.', hoursAgo: 67 },
    ],
  },
  {
    key: 't02',
    listingKey: 'l06',
    buyer: 'buyer2',
    messages: [
      { sender: 'buyer2', text: 'Salam, le prix est-il négociable pour l\'appartement Hay Riad ?', hoursAgo: 120 },
      { sender: 'sellerPro2', text: 'Bonjour, une petite marge est possible après visite.', hoursAgo: 118 },
      { sender: 'buyer2', text: 'Super, je peux visiter jeudi après-midi ?', hoursAgo: 115 },
    ],
  },
  {
    key: 't03',
    listingKey: 'l11',
    buyer: 'buyer3',
    messages: [
      { sender: 'buyer3', text: 'L\'iPhone a-t-il encore la garantie Apple ?', hoursAgo: 48 },
      { sender: 'sellerPro3', text: 'Garantie jusqu\'en mars 2027, facture disponible.', hoursAgo: 46 },
      { sender: 'buyer3', text: 'Batterie à combien de % ?', hoursAgo: 44 },
      { sender: 'sellerPro3', text: '92%, santé batterie vérifiée.', hoursAgo: 43 },
      { sender: 'buyer3', text: 'Je prends, on peut se voir à Maarif ?', hoursAgo: 40 },
    ],
  },
  {
    key: 't04',
    listingKey: 'l17',
    buyer: 'buyer1',
    messages: [
      { sender: 'buyer1', text: 'Magnifique tapis ! Livraison à Casablanca possible ?', hoursAgo: 200 },
      { sender: 'sellerPro4', text: 'Oui, livraison 150 DH sous 3 jours.', hoursAgo: 198 },
      { sender: 'buyer1', text: 'D\'accord, je réfléchis et je reviens vers vous.', hoursAgo: 190 },
    ],
  },
  {
    key: 't05',
    listingKey: 'l21',
    buyer: 'buyer4',
    messages: [
      { sender: 'buyer4', text: 'Le caftan est-il neuf ou occasion ?', hoursAgo: 96 },
      { sender: 'sellerPro5', text: 'Neuf, jamais porté. Essayage possible à Guéliz.', hoursAgo: 94 },
    ],
  },
  {
    key: 't06',
    listingKey: 'l26',
    buyer: 'buyer2',
    messages: [
      { sender: 'buyer2', text: 'Le canapé est-il démontable pour livraison ?', hoursAgo: 60 },
      { sender: 'sellerPro6', text: 'Oui, on peut le livrer et monter chez vous à Tanger.', hoursAgo: 58 },
      { sender: 'buyer2', text: 'Quel est le coût de livraison ?', hoursAgo: 55 },
      { sender: 'sellerPro6', text: '200 DH dans Tanger, 350 DH vers Tétouan.', hoursAgo: 54 },
    ],
  },
  {
    key: 't07',
    listingKey: 'l31',
    buyer: 'buyer3',
    messages: [
      { sender: 'buyer3', text: 'La poussette inclut-elle la nacelle ?', hoursAgo: 80 },
      { sender: 'sellerPro7', text: 'Oui, nacelle + hamac + housse pluie inclus.', hoursAgo: 78 },
    ],
  },
  {
    key: 't08',
    listingKey: 'l12',
    buyer: 'buyer1',
    messages: [
      { sender: 'buyer1', text: 'MacBook encore sous garantie ?', hoursAgo: 36 },
      { sender: 'sellerPro3', text: 'Oui, AppleCare+ jusqu\'à fin 2025.', hoursAgo: 34 },
      { sender: 'buyer1', text: 'Combien de cycles batterie ?', hoursAgo: 32 },
      { sender: 'sellerPro3', text: '87 cycles seulement.', hoursAgo: 31 },
      { sender: 'buyer1', text: 'OK, je suis intéressé. Paiement en plusieurs fois possible ?', hoursAgo: 28 },
      { sender: 'sellerPro3', text: '2 fois max, acompte 50% à la réservation.', hoursAgo: 27 },
    ],
  },
  {
    key: 't09',
    listingKey: 'l48',
    buyer: 'buyer4',
    messages: [
      { sender: 'buyer4', text: 'La C3 a combien de km exactement ?', hoursAgo: 20 },
      { sender: 'sellerPro1', text: '42 300 km, carnet d\'entretien complet.', hoursAgo: 18 },
    ],
  },
  {
    key: 't10',
    listingKey: 'l50',
    buyer: 'buyer2',
    messages: [
      { sender: 'buyer2', text: 'Le duplex est-il libre de suite ?', hoursAgo: 14 },
      { sender: 'sellerPro2', text: 'Libre à la signature, visites sur rendez-vous.', hoursAgo: 12 },
      { sender: 'buyer2', text: 'Charges de copropriété mensuelles ?', hoursAgo: 10 },
      { sender: 'sellerPro2', text: 'Environ 1 200 DH/mois.', hoursAgo: 9 },
    ],
  },
  {
    key: 't11',
    listingKey: 'l14',
    buyer: 'buyer3',
    messages: [
      { sender: 'buyer3', text: 'La PS5 est la version avec lecteur ?', hoursAgo: 8 },
      { sender: 'sellerPro3', text: 'Oui, édition disque, firmware à jour.', hoursAgo: 6 },
    ],
  },
  {
    key: 't12',
    listingKey: 'l39',
    buyer: 'buyer4',
    messages: [
      { sender: 'buyer4', text: 'Le vélo a-t-il été révisé récemment ?', hoursAgo: 50 },
      { sender: 'sellerReg1', text: 'Révision complète il y a 2 semaines, pneus neufs.', hoursAgo: 48 },
    ],
  },
  {
    key: 't13',
    listingKey: 'l08',
    buyer: 'buyer1',
    messages: [], // empty thread
  },
  {
    key: 't14',
    listingKey: 'l49',
    buyer: 'buyer2',
    messages: [], // empty thread
  },
  {
    key: 't15',
    listingKey: 'l52',
    buyer: 'buyer3',
    messages: [
      { sender: 'buyer3', text: 'Location pour un mariage en juillet, c\'est possible ?', hoursAgo: 5 },
      { sender: 'sellerPro5', text: 'Oui, location 3 jours à 2 500 DH.', hoursAgo: 4 },
      { sender: 'buyer3', text: 'Parfait, je réserve pour le 12 juillet.', hoursAgo: 3 },
      { sender: 'sellerPro5', text: 'Noté ! Je vous envoie les détails.', hoursAgo: 2 },
      { sender: 'buyer3', text: 'Merci beaucoup 🙏', hoursAgo: 1 },
    ],
  },
];

/** Order scenarios — only on APPROVED listings, buyer ≠ seller */
export const ORDER_SCENARIOS = [
  { key: 'o01', listingKey: 'l11', buyer: 'buyer1', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 30, shippingMad: 50 },
  { key: 'o02', listingKey: 'l17', buyer: 'buyer2', status: 'CONFIRMED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 25, shippingMad: 150 },
  { key: 'o03', listingKey: 'l21', buyer: 'buyer3', status: 'PENDING', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 5, shippingMad: 0 },
  { key: 'o04', listingKey: 'l26', buyer: 'buyer4', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 40, shippingMad: 200 },
  { key: 'o05', listingKey: 'l31', buyer: 'buyer1', status: 'CONFIRMED', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 18, shippingMad: 120 },
  { key: 'o06', listingKey: 'l01', buyer: 'buyer2', status: 'PENDING', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 3, shippingMad: 0 },
  { key: 'o07', listingKey: 'l12', buyer: 'buyer3', status: 'CANCELLED', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 22, shippingMad: 50 },
  { key: 'o08', listingKey: 'l39', buyer: 'buyer4', status: 'CONFIRMED', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 15, shippingMad: 0 },
  { key: 'o09', listingKey: 'l06', buyer: 'buyer1', status: 'PENDING', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 2, shippingMad: 0 },
  { key: 'o10', listingKey: 'l48', buyer: 'buyer3', status: 'CONFIRMED', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 12, shippingMad: 0 },
  { key: 'o11', listingKey: 'l14', buyer: 'buyer2', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 35, shippingMad: 80 },
  { key: 'o12', listingKey: 'l22', buyer: 'buyer4', status: 'PENDING', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 1, shippingMad: 40 },
  { key: 'o13', listingKey: 'l32', buyer: 'buyer1', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 28, shippingMad: 90 },
  { key: 'o14', listingKey: 'l40', buyer: 'buyer3', status: 'CONFIRMED', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 10, shippingMad: 0 },
  { key: 'o15', listingKey: 'l18', buyer: 'buyer2', status: 'CANCELLED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 45, shippingMad: 150 },
  { key: 'o16', listingKey: 'l49', buyer: 'buyer4', status: 'PENDING', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 4, shippingMad: 50 },
  { key: 'o17', listingKey: 'l50', buyer: 'buyer1', status: 'CONFIRMED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 8, shippingMad: 0 },
  { key: 'o18', listingKey: 'l51', buyer: 'buyer3', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 20, shippingMad: 180 },
  { key: 'o19', listingKey: 'l27', buyer: 'buyer2', status: 'SHIPPED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 50, shippingMad: 250 },
  { key: 'o20', listingKey: 'l33', buyer: 'buyer4', status: 'CONFIRMED', deliveryMethod: 'HOME', paymentMethod: 'CASH', daysAgo: 14, shippingMad: 60 },
  { key: 'o21', listingKey: 'l13', buyer: 'buyer1', status: 'CANCELLED', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 55, shippingMad: 0 },
  { key: 'o22', listingKey: 'l52', buyer: 'buyer2', status: 'PENDING', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 2, shippingMad: 0 },
  { key: 'o23', listingKey: 'l54', buyer: 'buyer3', status: 'CONFIRMED', deliveryMethod: 'HOME', paymentMethod: 'CARD', daysAgo: 6, shippingMad: 70 },
  { key: 'o24', listingKey: 'l03', buyer: 'buyer4', status: 'SHIPPED', deliveryMethod: 'PICKUP', paymentMethod: 'CASH', daysAgo: 16, shippingMad: 0 },
];

/** Favorites: buyer → listing keys */
export const FAVORITE_PAIRS = [
  ['buyer1', 'l06'], ['buyer1', 'l11'], ['buyer1', 'l17'], ['buyer1', 'l21'], ['buyer1', 'l48'], ['buyer1', 'l50'],
  ['buyer2', 'l01'], ['buyer2', 'l08'], ['buyer2', 'l12'], ['buyer2', 'l26'], ['buyer2', 'l50'], ['buyer2', 'l18'],
  ['buyer3', 'l11'], ['buyer3', 'l14'], ['buyer3', 'l31'], ['buyer3', 'l49'], ['buyer3', 'l52'], ['buyer3', 'l13'],
  ['buyer1', 'l02'], ['buyer1', 'l07'], ['buyer2', 'l06'], ['buyer2', 'l11'], ['buyer3', 'l17'], ['buyer3', 'l21'],
  ['buyer2', 'l27'], ['buyer3', 'l26'], ['buyer1', 'l31'], ['buyer2', 'l49'],
  ['buyer3', 'l39'], ['buyer1', 'l14'], ['buyer2', 'l31'],
];
// buyer4 (Tarik) intentionally has zero favorites — empty-state testing

export const DELIVERY_ADDRESSES = {
  buyer1: { fullName: 'Salma Harti', phone: '+212612345678', address: '12 Rue Ibn Khaldoun, Maarif', city: 'Casablanca', zip: '20250' },
  buyer2: { fullName: 'Adil Chakir', phone: '+212623456789', address: '45 Avenue Mohammed V, Agdal', city: 'Rabat', zip: '10000' },
  buyer3: { fullName: 'Houda Bensaid', phone: '+212634567890', address: '8 Rue de la Liberté, Guéliz', city: 'Marrakech', zip: '40000' },
  buyer4: { fullName: 'Tarik El Ghazi', phone: '+212645678901', address: '3 Boulevard Hassan II', city: 'Tanger', zip: '90000' },
};
